name: Get Citation Data

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - google_scholar_crawler/**
      - .github/workflows/google_scholar_crawler.yaml
  schedule:
    - cron: '0 8 * * *'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Run
      run: |
        cd ./google_scholar_crawler
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        python3 main.py
        cd ./results
        git init
        git config --local user.name "${GITHUB_ACTOR}"
        git config --local user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        export remote_repo="https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
        git add *.json
        git commit -m "Updated Citation Data"
        git push "${remote_repo}" HEAD:google-scholar-stats --force
      env: 
        GOOGLE_SCHOLAR_ID: ${{ secrets.GOOGLE_SCHOLAR_ID }}
